# _config.yml
title: Tonka Track & Field
description: Building champions, one stride at a time
baseurl: "/TonkaTrack"
url: "https://nolanerpelding.github.io"

# Permalink style (removes .html)
permalink: pretty

# Exclude files from processing
exclude:
  - README.md
  - .gitignore